### ISSUE TITLE
Display interpreted input

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#13]
The desktop version has this feature where it shows the actual input it interpreted. For example, when it guesses the location of braces, it shows where they are.

Not sure if this is something that should be displayed all the time, as it is duplicate information when using it as a simple calculator. Should this be only on some screens? Only when expanding some area of the screen? Not really sure.

**Comment by mr-kenhoff** [comment]
I think something along that line is an absolute requirement. 

Additionally, some sort of auto-completion - like we have it in the desktop version - would be really nice. At least for the "free text input" mode. Of course this is not needed if we only use predefined buttons

**Comment by jherkenhoff** [comment]
Done
