### ISSUE TITLE
Secondary button actions

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#17]
https://github.com/mr-kenhoff/qalculate-android/issues/15#issuecomment-1080036269

> When it comes to the buttons, I thought about some kind of "swipe buttons", as there are for example used in the Unexpected Keyboard: https://github.com/Julow/Unexpected-Keyboard

**Comment by ByteHamster** [comment]
My keyboard uses long-press to show secondary buttons. That could be an option which is maybe more familiar for users. In any case, displaying the secondary actions clutters the screen. I think it might be useful to have an option to disable them. Maybe it could even be disabled by default.

**Comment by jherkenhoff** [comment]
Currently not longer relevant/possible because of UI design overhaul focussing on keyboard input
