### ISSUE TITLE
`abiFilters` is duplicated

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#22]
The `abiFilters` Gradle property is specified in both the app and the library. After upgrading the library, I was no longer able to run the app on my phone:

> Installation failed due to: 'INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries'

After adding `arm64-v8a` to the library module, it started to work again. This makes me think that the filter is actually not needed for the app, only for the library. In any case, if there are two filters, they should both be synchronized.

**Comment by mr-kenhoff** [comment]
Ahh yes, the ABI filter in the library is actually not needed. I just added it to not have to compile for an eternity.
The ABI filter in the qalculate app is actually needed for some strange reason: Without it, the NDK libraries do not get packed into the APK when clicking the "play-button" in AndroidStudio.

**Comment by JJRcop** [comment]
I also have trouble installing Qalculate! on my phone, which features the `arm64-v8a` ABI, with this issue.

**Comment by jherkenhoff** [comment]
Removed ABI filter
