### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#30]
Most calculators I tried simply limit the app to portrait mode. We should either do that or add other layouts for landscape mode.

**Comment by jherkenhoff** [comment]
Since I do not have a good idea for landscape mode, I would fix the orientation to portrait mode for the time being.

[c8216ca](https://github.com/jherkenhoff/qalculate-android/commit/c8216ca6c9c021cf7db714ea6501772187eebe4c)
