### ISSUE TITLE
qalc CLI mode

### ISSUE THREAD

**Issue by JJRcop** [jherkenhoff/qalculate-android#34]
I think it would be useful to feature a mode which opens a terminal connected up to the libqalculate shell/qalc, so you can use the app like qalc if you wish to. The terminal would pull up the keyboard and let you start typing. In this mode typing in a command does not evaluate it live until you press enter or OK, so it functions like if you ran the qalc program on PC.

**Comment by jherkenhoff** [comment]
This is mostly how the app now works after my latest rewrite. Currently, the input is evaluated live, but I plan on having an option to switch that off
