### ISSUE TITLE
Handle results display overflow

### ISSUE THREAD

**Issue by jherkenhoff** [jherkenhoff/qalculate-android#42]

**Comment by jherkenhoff** [comment]
Fixed in #8dfcb1e7477978cb39a2034d748125a0d3032582

**Comment by jherkenhoff** [comment]
Thanks to @inidamleader for the implementation of the [AutoSizeText](https://gist.github.com/inidamleader/b594d35362ebcf3cedf81055df519300)
@indamleader if you are ok with it, I would add you to the list of contributors since your gist saved me a ton of time! But I would also respect if you dont want to :)

**Comment by inidamleader** [comment]
Thank you, yes of course, that will be an honor for me.

**Comment by jherkenhoff** [comment]
@all-contributors please add @inidamleader for code

**Comment by jherkenhoff** [comment]
@all-contributors please add @inidamleader for code
