### ISSUE TITLE
Focus input field on startup

### ISSUE THREAD

**Issue by jherkenhoff** [jherkenhoff/qalculate-android#47]
It would make sense to be greeted with either the keyboard or the altKeyboard when starting the app. For this, the last open keyboard has to be remembered

**Comment by ByteHamster** [comment]
Hi, it has been a while since I contributed here. I'm using (an old branch of) this app on a daily basis and really love it.

Should it really remember the last opened keyboard? Personally, I really like to have the simple number pad as a default and only rarely switch to the full keyboard. Remembering would mean that I have to switch back to the number pad whenever I need the full features.

**Comment by jherkenhoff** [comment]
I understand your comment. I find myself falling back to the stock android calculator for the day-to-day calculations because I mostly need the most simple operations (+,-,÷,×, maybe a bracket here and there), and the keyboard screen is not the most convenient for that.

But don't you think remembering the last used screen would solve that? Another option would be to have an option for the default screen in the (currently non existent) user settings menu

**Comment by ByteHamster** [comment]
> I find myself falling back to the stock android calculator for the day-to-day calculations because I mostly need the most simple operations

That's what I love about the old branch that I'm still using. By default, it's a simple day-to-day calculator, but it still has the full power if I need it

> But don't you think remembering the last used screen would solve that?

I think it would mostly solve it, but not fully. I don't want to have to switch back if I come back to the calculator a few days later

> Another option would be to have an option for the default screen in the (currently non existent) user settings menu

For me, that would be perfect. However, I know that users constantly request all kinds of settings, so not sure if my use-case would be worth it.
