### ISSUE TITLE
Always display numeric result, not `interval(x,y)`

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#5]
When entering `pi`, for example, the app displays `interval(x,y)`. I think it should display only the number instead.

**Comment by mr-kenhoff** [comment]
Yes, this will be handled by the Qalculate-internal print options

**Comment by jherkenhoff** [comment]
Fixed in https://github.com/jherkenhoff/qalculate-android/pull/31

**Comment by jherkenhoff** [comment]
Well, this is a hardcoded quick fix. The interval display should be an option in a settings dialog
