### ISSUE TITLE
Pressing "=" button on AltKeyboard does not add history item

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#52]
The "=" button should behave similar to the return button on the keyboard and add the item to the history

**Comment by jherkenhoff** [comment]
Maybe it should also not be an "=" symbol but a return symbol (↵) or something else?

I think there should also be some additional buttons above the number block for brackets, squares, etc. which maybe should also house an equal symbol to really enter an "=" into the text input
