### ISSUE TITLE
Monochrome icon

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#54]
Material You optionally uses monochrome icons that adapt to the wallpaper color. Is the current (colorful) icon final? Then I can have a look at creating a monochrome version

**Comment by jherkenhoff** [comment]
Since I do not use material-you colored icons I did not notice the need for a monochrome version, so thanks for that suggestion 👍 Yes, I would consider the current icon final, so if you feel like creating one that would be amazing
