### ISSUE TITLE
Trigonometric functions

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#6]
`sin`, `cos`, etc are currently not interpreted. The result simply is the text that was entered. My guess would be that this is because the app does not specify radians vs degrees.

**Comment by smm9509** [comment]
The behaivor you describe is consistent with qalc when the angle setting is set to 0.

See the "settings" section here https://qalculate.github.io/manual/qalc.html

This is set by the "/set angle [number]" qalc command. When the number is zero, the units of the argument for all trigonometric functions must be an angle (e.g. cos(pi rad), sin(45 deg), tan(1023.4 turns)). This is my preferred setting, and I assume it's also the default in this app. I haven't actually used this app yet but I'm thinking about trying it.

**Comment by jherkenhoff** [comment]
Fixed in [bfff519](https://github.com/jherkenhoff/qalculate-android/commit/bfff5194b0022db274ba492a10acbd6f3e8c1f89)
