### ISSUE TITLE
Unable to close keyboard

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#63]
When trying to close the keyboard, for example to view the calculation history on the full screen, it immediately pops back open.

**Comment by jherkenhoff** [comment]
I think I already fixed this in the `autocomplete` branch in commit b99585bac80e164b38ea3a2d9915ec7a6b36b76b. I now merged it to `main`. 

When you have time, can you check if it solves this problem?

**Comment by ByteHamster** [comment]
Thanks, solved
