### ISSUE TITLE
Text input box behaves in unexpected way

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#64]
There are two issues with the soft keyboard behaving in an unexpected way. I can reproduce one of them using the AOSP keyboard. My guess would be that both issues are caused by the same problem and that this is related to Compose re-layouting the screen.

## 1. Clearing
When I type quickly, the text input box is sometimes cleared. I can only reproduce this with the HeliBoard keyboard, not with the AOSP keyboard.

![screen-20240925-210640 mp4](https://github.com/user-attachments/assets/c81aef91-9c70-4c3f-a787-4d7344f92e04)

## 2. Switching back from special keys
With all other apps, when I switch to the special keys and press one of them, the keyboard stays in the special keys mode. On Qalculate, it switches back to the main keys. I can reproduce this with the AOSP keyboard. It looks like Qalculate somehow re-initializes the keyboard after each button press.

![screen-20240925-211326 mp4](https://github.com/user-attachments/assets/07b4ca6c-ab37-4036-9158-d8c5b1c5a867)

**Comment by jherkenhoff** [comment]
That's indeed very strange behaviour. Can you check again with the latest version in main?
I got rid of unnecessary full-screen recompositions when updating the calculation result (i.e. each time a character is pressed), which maybe could have caused this.

**Comment by ByteHamster** [comment]
Thanks, the problem is solved on the main branch.
