### ISSUE TITLE
Display variables differently

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#7]
Currently, unknown variables are printed with quotes. They should maybe get a different color or font. This can probably be done with `SpannableString`.

Example input: `2*b`
Current output: `2'b'`
Expected output: something like "2**b**"

**Comment by mr-kenhoff** [comment]
Yes, good idea. Same thing for units maybe

**Comment by jherkenhoff** [comment]
Implemented in [bfff519](https://github.com/jherkenhoff/qalculate-android/commit/bfff5194b0022db274ba492a10acbd6f3e8c1f89)
