### ISSUE TITLE
Nothing works except calculator 

### ISSUE THREAD

**Issue by dziban303** [jherkenhoff/qalculate-android#79]
I realize this is an early release, I'm using 0.1.1 from fdroid, but is it intentional that none of the buttons or other functions work? The Functions, Variables, and Datasets buttons in the hamburger menu don't work at all, nor does Settings. They animate when tapped but nothing happens. The Units button does open the units list, and I can type in the search box, but nothing else works. Plus button, tapping on the unit names, the filter button, the categories—nothing works.

If that's not intentional behavior, let me know if there's anything you'd like me to do to troubleshoot. I'm using a Pixel 6a, Android 14.

**Comment by jkimsis** [comment]
I have the same problem, Samsung A64, Android 14, OneUI 6.1. I'm using the Qalculate version 0.1.1 from F-droid

**Comment by UlyssesZh** [comment]
I think this is intended. You can see [here](https://github.com/jherkenhoff/qalculate-android/blob/e35878e8e10a9381124fe46125b8036cf5cf0a96/app/src/main/java/com/jherkenhoff/qalculate/ui/QalculateNavigation.kt) that all navigations except units and calculator are undefined.

**Comment by UlyssesZh** [comment]
I think there should be a toast saying that these features are unimplemented when those navigations are tapped. This can avoid confusion.

**Comment by jherkenhoff** [comment]
Very true. I have put these Items there while designing the navigation drawer and forgot to remove them on the first release.
Showing a toast is a good Idea.
